// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMySXTrUYoyBMf-QiBMlexG5doY1lq79g',
    appId: '1:149631071463:web:a8067234e5969540ffde42',
    messagingSenderId: '149631071463',
    projectId: 'e-charts-28f03',
    authDomain: 'e-charts-28f03.firebaseapp.com',
    storageBucket: 'e-charts-28f03.appspot.com',
    measurementId: 'G-E0J74NLGZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-B1zy3_X9HPu7jUTQLddGKOB_G_zYDzM',
    appId: '1:149631071463:android:57987544e42be119ffde42',
    messagingSenderId: '149631071463',
    projectId: 'e-charts-28f03',
    storageBucket: 'e-charts-28f03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhQESFo9fVPQwcfy5leV6J_zJajwXXJEE',
    appId: '1:149631071463:ios:a221d8fb9fe93c7cffde42',
    messagingSenderId: '149631071463',
    projectId: 'e-charts-28f03',
    storageBucket: 'e-charts-28f03.appspot.com',
    iosClientId: '149631071463-ro48ma66068c819l77cc8tviuaksak5v.apps.googleusercontent.com',
    iosBundleId: 'com.e-charts.app',
  );
}
